<div>
    <ul>
        <li><a href="<?php echo $this->url('calculator\calculator\index'); ?>">Inicio</a></li>
        <li><a href="<?php echo $this->url('calculator\calculator\add'); ?>">Add</a></li>
        <li><a href="<?php echo $this->url('calculator\calculator\substract'); ?>">Substract</a></li>
        <li><a href="<?php echo $this->url('calculator\calculator\multiply'); ?>">Multiply</a></li>
        <li><a href="<?php echo $this->url('calculator\calculator\division'); ?>">Division</a></li>
    </ul>
</div>