<div>
    <table>
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Password</th>
            <th>Role</th>
            <th>Date</th>
        </tr>
        <?php foreach($this->users as $user): ?>
        <tr>
            <td><?php echo $this->escapeHtml($user->getId()); ?></td>
            <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
            <td><?php echo $this->escapeHtml($user->getPassword()); ?></td>
            <td><?php echo $this->escapeHtml($user->getRole()); ?></td>
            <td><?php echo $this->escapeHtml($user->getDate()); ?></td>
            <td><a href="<?php echo $this->url('user\account\view', ['id' => $user->getId()]) ?>">View</a></td>
            <td><a href="<?php echo $this->url('user\account\update', ['id' => $user->getId()]) ?>">Update</a></td>
            <td><a href="<?php echo $this->url('user\account\delete', ['id' => $user->getId()]) ?>">Delete</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<div>
    <p><a href="<?php echo $this->url('user\account\create') ?>">Create a new Account</a> </p>
</div>