<div class="jumbotron">
    <h1><span class="zf-green">ZF2 Course</span> by Ismael Trascastro</h1>
    <p>In this course you will practice with the main components of Zend Framework in order to achieve a solid knowledge of the framework</p>
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-success btn-lg" href="https://bitbucket.org/itrascastro/zf2-course">Bitbucket</a>
            <a class="btn btn-primary btn-lg" href="https://github.com/itrascastro">GitHub</a>
            <a class="btn btn btn-info btn-lg" href="https://twitter.com/trascastro">Twitter</a>
            <a class="btn btn-danger btn-lg" href="https://www.youtube.com/watch?v=OKot73E8uh4&list=PLI-8Ih7owqqcoiKCFemhKaAgBgOtZJ367">Youtube</a></div>
    </div>
</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 1 - Modules</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Installation</li>
                    <li>Directory Structure</li>
                    <li>Configuration</li>
                    <li>Module Creation</li>
                    <li>Dependency Injection</li>
                    <li>Calculator Module</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-1">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/OKot73E8uh4">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 2 - Modules II</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Factories</li>
                    <li>Service Manager</li>
                    <li>Inversion of Control</li>
                    <li>Module.php to reuse code</li>
                    <li>Exercise: MyString</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-2">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/1Oe8Fm2bGII">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 3 - MVC</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Layouts</li>
                    <li>Layout Variables</li>
                    <li>onBootstrap</li>
                    <li>Using View Helpers</li>
                    <li>Partial View Helper</li>
                    <li>Creating View Helpers</li>
                    <li>Sharing Views in Actions</li>
                    <li>Different layouts per module</li>
                    <li>Static Content Allocation</li>
                    <li>When Creating Modules</li>
                    <li>Controller Plugins</li>
                    <li>Creating Controller Plugins</li>
                    <li>Zend Tool</li>
                    <li>Exercise: MyString</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-3">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/FqxQBcj-ff0">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 4 - Database PDO</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>DB Configuration</li>
                    <li>Entity Creation</li>
                    <li>PDO</li>
                    <li>DAO Model</li>
                    <li>CRUD Users</li>
                </ul>
                <p><a class="btn btn-success col-lg-pull-0" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-4">Source code &raquo;</a></p>
                <p><a class="btn btn-danger col-lg-pull-1" href="http://youtu.be/Mu5v113YAT0">Video1 &raquo;</a></p>
                <p><a class="btn btn-danger col-lg-pull-2" href="http://youtu.be/IH9AL_yXpJI">Video2 &raquo;</a></p>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 5 - TableGateway</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>TableGateway Configuration</li>
                    <li>Entity exchangeArray</li>
                    <li>DAO Model</li>
                    <li>CRUD Users</li>
                    <li>Zend\Db\Sql</li>
                    <li>Exercise: Bookmarks CRUD</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-5">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/m1jf6vj6cis">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 6 - Zend\Form</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Creating Forms</li>
                    <li>Form Filters</li>
                    <li>Form Validators</li>
                    <li>Using Forms in Controllers</li>
                    <li>Form View Helpers</li>
                    <li>Refactoring User Forms</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-6">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/5viGByLUe0E">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 7 - Authentication</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Authentication Service</li>
                    <li>Auth Adapter</li>
                    <li>Auth Storage</li>
                    <li>Login Controller</li>
                    <li>Login Form</li>
                    <li>Login View</li>
                    <li>ACL EVENT_ROUTE</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-7">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/laXMF9QYs-I">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 8 - ACL</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>ACL Service Factory</li>
                    <li>Using ACL in EVENT_ROUTE</li>
                    <li>ACL in Views</li>
                    <li>ACL in Controllers</li>
                    <li>Exercise: ACL in Bookmarks</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-8">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/Szd1wQTT0I0">Video &raquo;</a></p>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 9 - Pagination</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Zend\Paginator</li>
                    <li>Exercise: Bookmarks App I</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-9">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/du9Gn7RNLuU">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 10 - Ajax</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>AJAX CRUD</li>
                    <li>Exercise: Bookmarks App II</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-10">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/laXMF9QYs-I">Video &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
