<div class="jumbotron">
    <h1><span class="zf-green">ZF2 Course</span> by Ismael Trascastro</h1>
    <p>In this course you will practice with the main components of Zend Framework in order to achieve a solid knowledge of the framework</p>
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-success btn-lg" href="https://bitbucket.org/itrascastro/zf2-course">Bitbucket</a>
            <a class="btn btn-primary btn-lg" href="https://github.com/itrascastro">GitHub</a>
            <a class="btn btn btn-info btn-lg" href="https://twitter.com/trascastro">@trascastro</a>
            <a class="btn btn-danger btn-lg" href="https://www.youtube.com/user/ismael3334/">Youtube</a></div>
    </div>
</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 1</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 2</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 3</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 4</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 5</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 6</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 7</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 8</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 9</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 10</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
