<div class="jumbotron">
    <h1><span class="zf-green">ZF2 Course</span> by Ismael Trascastro</h1>
    <p>In this course you will practice with the main components of Zend Framework in order to achieve a solid knowledge of the framework</p>
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-success btn-lg" href="https://bitbucket.org/itrascastro/zf2-course">Bitbucket</a>
            <a class="btn btn-primary btn-lg" href="https://github.com/itrascastro">GitHub</a>
            <a class="btn btn btn-info btn-lg" href="https://twitter.com/trascastro">Twitter</a>
            <a class="btn btn-danger btn-lg" href="https://www.youtube.com/user/ismael3334/">Youtube</a></div>
    </div>
</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 1 - Modules</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Installation</li>
                    <li>Directory Structure</li>
                    <li>Configuration</li>
                    <li>Module Creation</li>
                    <li>Dependency Injection</li>
                    <li>Calculator Module</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-1">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/OKot73E8uh4">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 2 - Modules II</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Factories</li>
                    <li>Service Manager</li>
                    <li>Inversion of Control</li>
                    <li>Module.php to reuse code</li>
                    <li>Exercise: MyString</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-2">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/1Oe8Fm2bGII">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 3 - MVC</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Layouts</li>
                    <li>Layout Variables</li>
                    <li>onBootstrap</li>
                    <li>Using View Helpers</li>
                    <li>Partial View Helper</li>
                    <li>Creating View Helpers</li>
                    <li>Sharing Views in Actions</li>
                    <li>Different layouts per module</li>
                    <li>Static Content Allocation</li>
                    <li>When Creating Modules</li>
                    <li>Controller Plugins</li>
                    <li>Creating Controller Plugins</li>
                    <li>Zend Tool</li>
                    <li>Exercise: MyString</li>
                </ul>
                <p><a class="btn btn-success pull-left" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-3">Source code &raquo;</a></p>
                <p><a class="btn btn-danger pull-right" href="http://youtu.be/FqxQBcj-ff0">Video &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 4</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="https://bitbucket.org/itrascastro/zf2-course/src/?at=session-4">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 5</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 6</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 7</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 8</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 9</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Session 10</h3>
            </div>
            <div class="panel-body">
                <p>Description</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Source code &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
